---
- name: Update apt cache
  ansible.builtin.apt:
    cache_valid_time: 3600

- name: Install Redis
  notify: Start Redis
  ansible.builtin.apt:
    name: redis-server

- when: redis.replication.sentinel
  block:
    - name: Install Redis Sentinel
      ansible.builtin.apt:
        name: redis-sentinel
      register: redis_install_sentinel_apt_result

    - name: Stop Redis Sentinel
      when: redis_install_sentinel_apt_result.changed
      ansible.builtin.service:
        name: "{{ redis.service.sentinel }}"
        state: stopped
