---
- name: Install Redis
  ansible.builtin.include_tasks: install.yaml

- name: Configure Redis service
  ansible.builtin.include_tasks: service.yaml

- name: Configure Redis
  ansible.builtin.include_tasks: config.yaml
