---
- name: Install Redis
  ansible.builtin.include_tasks: install.yaml
  when: ansible_facts['os_family'] == "Debian"

- name: Configure Redis service
  ansible.builtin.include_tasks: service.yaml

- name: Configure Redis
  ansible.builtin.include_tasks: config.yaml

- name: Configure Logrotate for Redis
  ansible.builtin.include_tasks: logrotate.yaml
