---
- name: Enable Redis service
  ansible.builtin.service:
    name: "{{ redis.service.server }}"
    enabled: yes

- name: Enable Redis Sentinel
  when:
    - redis.replication.sentinel
  ansible.builtin.service:
    name: "{{ redis.service.sentinel }}"
    enabled: yes
